let languageContent = {
    en: {
        "nav-home": "Home",
        "nav-about": "About",
        "nav-projects": "Projects",
        "nav-resume": "Resume",
        "nav-contact": "Contact",
        welcome: "Welcome",
        iam: "I<span>'</span>m",
        "title-1": "Web Developer",
        "title-2": "Graphic Designer",
        "title-3": "UI/UX Designer",
        download: "Download CV",
        "about-title": "About",
        "about-text-1":
            "Hello, I'm Khaidar, a Graphic Designer and Web Developer. I have expertise in Front-End (HTML, CSS, JS, Bootstrap), Back-End (Python), and Graphic Design (Photoshop, Illustrator). In addition, I also have additional skills in UI/UX Design (Figma) and IoT.",
        "about-text-2":
            "I have worked in several communities as a Graphic Designer. I am very enthusiastic about developing my skills and seeking opportunities to work in a company that allows me to learn and contribute.",
        "about-text-3":
            "Thank you for visiting my website. I hope to collaborate with you on interesting and beneficial projects. Please don't hesitate to contact me if you have any questions or would like to discuss further how I can help you.",
        my: "My",
        "skills-2": "Skills",
        learning: "Currently Learning",
        "inter-1": "Intermediate",
        "inter-2": "Intermediate",
        "inter-3": "Intermediate",
        advanced: "Advanced",
        "projects-title": "Projects",
        "project-1": "Kora-Kora Festival Poster 2023",
        "project-2": "Instagram Feeds - 8 Most Important Figures Contributed to the Internet World",
        "project-3": "Instaram Feeds - JavaScript Animation Libraries",
        "project-4": "Instagram Feeds - Python Tips & Tricks",
        "project-5": "Community Poster - S3 Show",
        "project-6": "Website Project - ShortLink",
        "project-7": "UI Design - Tourism Website",
        "project-8": "Community Fest Poster",
        "project-9": "Community Fest Logo",
        "resume-title": "Resume",
        "resume-capt":
            "In this section, you will find my educational background and work experience. I believe that my academic achievements and professional experiences have equipped me with the necessary skills and knowledge to excel in the field. I am a firm believer in continuous learning, and I strive to apply my skills to create impactful solutions. Please take a look at my educational qualifications and work history to learn more about my journey so far.",
        "edu-title": "Education",
        "edu-1": "Muhammadiyah Senior High School of Ternate City",
        "edu-1-award-1": "2nd Winner of Kihajar Quiz at City Level",
        "edu-1-award-2": "3rd Winner of National Science Olympiad in Economics at City Level",
        "edu-1-award-3": "3rd Winner of National Science Olympiad in Economics at Provincial Level",
        "edu-1-award-4": "5th Rank in Accounting Olympiad at City Level",
        "edu-2": "Muhammadiyah University of North Maluku",
        "edu-2-award-1": "1st Winner of University-Level UI/UX Design Competition",
        "edu-2-award-2": "2nd Winner of University-Level English Speech Competition",
        "edu-2-award-3": "2nd Winner of National-Level Game Programming Competition",
        "edu-2-award-4": "3rd Winner of University-Level Coding Challenge Competition",
        "edu-2-award-5": "Ranked 14th in National-Level UI/UX Design Contest",
        exp: "Experience",
        "it-staff": "IT Staff",
        "present-1": "Present",
        "present-2": "Present",
        "present-3": "Present",
        jarkot: "Ternate Creative Space (previously JARKOT)",
        "graphic-1": "Graphic Designer",
        "graphic-2": "Graphic Designer",
        "contact-title": "Contact",
        "contact-text":
            'Feel free to reach out to me via email or social media. I am always open to new <span class="highlight">opportunies</span> and <span class="highlight" >collaborations</span>',
        "add-1": "Sasa Subdistrict, STKIP Street",
        "add-2": "South Ternate, Ternate City, Indonesia",
        send: "Send",
        created: "Created by Eternal Code",
    },
    id: {
        "nav-home": "Beranda",
        "nav-about": "Tentang",
        "nav-projects": "Proyek",
        "nav-resume": "Ringkasan",
        "nav-contact": "Kontak",
        "welcome": "Selamat Datang",
        "iam": "Saya",
        "title-1": "Web Developer",
        "title-2": "Graphic Designer",
        "title-3": "UI/UX Designer",
        "download": "Unduh CV",
        "about-title": "Tentang",
        "about-text-1":
            "Halo, saya Khaidar, seorang Desainer Grafis dan Pengembang Web. Saya memiliki keahlian di Front-End (HTML, CSS, JS, Bootstrap), Back-End (Python), dan Desain Grafis (Photoshop, Illustrator). Selain itu, saya juga memiliki keterampilan tambahan di Desain UI/UX (Figma) dan IoT.",
        "about-text-2":
            "Saya pernah bekerja di beberapa komunitas sebagai Desainer Grafis. Saya sangat antusias dalam mengembangkan kemampuan saya dan mencari kesempatan untuk bekerja di perusahaan yang memungkinkan saya untuk belajar dan berkontribusi.",
        "about-text-3":
            "Terima kasih telah mengunjungi website saya. Saya berharap dapat berkolaborasi dengan Anda dalam proyek yang menarik dan bermanfaat. Jangan ragu untuk menghubungi saya jika Anda memiliki pertanyaan atau ingin membahas lebih lanjut bagaimana saya dapat membantu Anda.",
        "my": "Keahlian",
        "skills-2": "Saya",
        "learning": "Sedang dipelajari",
        "inter-1": "Menengah",
        "inter-2": "Menengah",
        "inter-3": "Menengah",
        "advanced": "Tingkat Lanjut",
        "projects-title": "Proyek",
        "project-1": "Poster Festival Kora-Kora 2023",
        "project-2": "Instagram Feeds - 8 Tokoh Penting yang Berjasa di Dunia Internet",
        "project-3": "Instaram Feeds - JavaScript Animation Libraries",
        "project-4": "Instagram Feeds - Python Tips & Tricks",
        "project-5": "Poster Komunitas - S3 Show",
        "project-6": "Website Project - ShortLink",
        "project-7": "UI Design - Website Pariwisata",
        "project-8": "Poster Festival Komunitas",
        "project-9": "Logo Festival Komunitas",
        "resume-title": "Ringkasan",
        "resume-capt":
            "Berikut adalah latar belakang pendidikan dan pengalaman kerja saya. Saya percaya bahwa prestasi akademik dan pengalaman profesional saya telah membekali saya dengan keterampilan dan pengetahuan yang diperlukan untuk menjadi unggul di bidang ini. Saya sangat mempercayai pembelajaran berkelanjutan, dan saya berusaha untuk menerapkan keterampilan saya untuk menciptakan solusi yang berdampak positif. Silakan lihat kualifikasi pendidikan dan riwayat kerja saya untuk mempelajari lebih lanjut tentang perjalanan saya selama ini.",
        "edu-title": "Pendidikan",
        "edu-1": "SMA Muhammadiyah Kota Ternate",
        "edu-1-award-1": "Juara 2 Kuis Kihajar Tingkat Kota",
        "edu-1-award-2": "Juara 3 Olimpiade Sains Nasional Ekonomi Tingkat Kota",
        "edu-1-award-3": "Juara 3 Olimpiade Sains Nasional Ekonomi Tingkat Provinsi",
        "edu-1-award-4": "Peringkat 5 Olimpiade Akuntansi Tingkat Kota",
        "edu-2": "Universitas Muhammadiyah Maluku Utara",
        "edu-2-award-1": "Juara 1 Lomba UI/UX Design Tingkat Universitas",
        "edu-2-award-2": "Juara 2 Lomba Pidato Bahasa Inggris Tingkat Universitas",
        "edu-2-award-3": "Juara 2 Lomba Pemrograman Game Tingkat Nasional",
        "edu-2-award-4": "Juara 3 Lomba Coding Challenge Tingkat Universitas",
        "edu-2-award-5": "Peringkat 14 Kontes UI/UX Design Tingkat Nasional",
        "exp": "Pengalaman",
        "it-staff": "Staf IT",
        "present-1": "Sekarang",
        "present-2": "Sekarang",
        "present-3": "Sekarang",
        "jarkot": "Ternate Creative Space (sebelumnya JARKOT)",
        "graphic-1": "Graphic Designer",
        "graphic-2": "Graphic Designer",
        "contact-title": "Kontak",
        "contact-text":
            'Jangan ragu untuk menghubungi saya melalui email atau media sosial. Saya selalu terbuka untuk <span class="highlight">kesempatan</span> dan <span class="highlight">kolaborasi</span> baru.',
        "add-1": "Jl.STKIP, Kel.Sasa",
        "add-2": "Ternate Selatan, Kota Ternate, Indonesia",
        "send": "Kirim",
        "created": "Dibuat oleh Eternal Code",
    },
};
function switchLang(lang) {
    for (let key in languageContent[lang]) {
        document.getElementById(key).innerHTML = languageContent[lang][key];
    }
}
